apiVersion: batch/v1
kind: CronJob
metadata:
  name: date
spec:
  schedule: "*/2 * * * *" # 2分ごとに実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: date
            image: ubuntu:22.04
            command: ["date"]
          restartPolicy: Never