apiVersion: v1
kind: Pod
metadata:
  name: pod-anti-affinity
  labels:
    app: nginx
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution: # スケジューリング中に適用、実行中は無視のルール設定
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nginx
          topologyKey: kubernetes.io/hostname # Affinity等を適用させる、Pod 配置制御。ホスト以外にゾーンやリージョンでも指定可能
  containers:
  - name: nginx
    image: nginx:1.25.3