apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec: # Nodeについているラベルがdisktype valueがSSDであればそのNodeにスケジュールされる、ただし対応するNodeがなくともPodはスケジュールされる
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  containers:
  - name: node-affinity-pod
    image: nginx:1.25.3